# Imports

In [6]:
import numpy as np
import pandas

# Numpy Theory

NumPy was created in 2005 by **Travis Oliphant**. NumPy stands for **Numerical Python**.

## Theory Topics

1. Use of 'array' function (for creating an array)
2. Array Indexing
3. Array Slicing
4. Numpy Data Types
5. Shape
6. Reshape
7. Iterating (for loop, nditer(array), ndenumerate(array))
8. Join (`concatenate()`, `stack()`, `hstack()`, `vstack()`, `dstack()`)
9. Split (`array_split()`, `hsplit()`, `vsplit()`, `dsplit()`)
10. Search-Where (`where()`, `searchsorted()`)
11. Sort (`sort()`)
12. Filtering (filter an array using a boolean index list.)
13. Random (`shuffle`, `permutation`, `randint`, `rand`)
14. Arithmetic ufuncs (`add`, `subtract`, `multiply`, `divide`, `power`, `mod()` or `reminder()`, `divmod()`, `absolute()` or `abs()`)

## Notes

- `random.shuffle` and `random.permutation` functions have the same functionality, but `permutation()` creates a new array.

## Terminology

- `ufuncs` = Universal Functions (`<class 'numpy.ufunc'>`)
- Vectorization = Converting iterative statements into a vector-based operation is called vectorization.


# Numpy Practice

In [5]:
# 0-D Array
print("0-D Array")
arr = np.array(42)
print(arr)
print("Dimension : ", arr.ndim)

# 1-D Array
print("\n1-D Array")
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print("Dimension : ", arr.ndim)

# 2-D Array
print("\n2-D Array")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("Dimension : ", arr.ndim)

# 3-D Array (3-D array contains list of 2-D arrays)
print("\n3-D Array")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print("Dimension : ", arr.ndim)

0-D Array
42
Dimension :  0

1-D Array
[1 2 3 4 5]
Dimension :  1

2-D Array
[[1 2 3]
 [4 5 6]]
Dimension :  2

3-D Array
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension :  3


**Numpy Data Types** :
```
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
```

Check data type of an array by using **dtype**.

